import type { Config } from "tailwindcss";
import tailwindAnimate from "tailwindcss-animate";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "surface-container-highest": "#d9e2ff",
        "on-secondary-fixed": "#00483d",
        "surface-variant": "#d9e2ff",
        "surface-dim": "#cdd9ff",
        "on-primary-container": "#35279b",
        "error-dim": "#770326",
        "on-tertiary-container": "#4400a0",
        "primary-dim": "#4d42b2",
        "on-error-container": "#68001f",
        "surface": "#faf8ff",
        "on-secondary-fixed-variant": "#006859",
        "inverse-surface": "#060e20",
        "tertiary-fixed": "#c4abff",
        "primary-fixed-dim": "#b1aaff",
        "surface-tint": "#594fbf",
        "brand-secondary": "#006c5c",
        "tertiary": "#7000ff",
        "surface-container-low": "#f2f3ff",
        "tertiary-container": "#c4abff",
        "primary-container": "#bfb9ff",
        "on-error": "#fff7f7",
        "error": "#ac3149",
        "secondary-fixed-dim": "#00efce",
        "on-surface": "#213156",
        "secondary-container": "#26fedc",
        "on-primary-fixed": "#1f0287",
        "on-primary": "#fcf7ff",
        "inverse-on-surface": "#959cb5",
        "on-secondary-container": "#005d4f",
        "secondary-fixed": "#26fedc",
        "tertiary-dim": "#6200e1",
        "brand-primary": "#594fbf",
        "tertiary-fixed-dim": "#b89bff",
        "surface-container-high": "#e2e7ff",
        "on-tertiary-fixed": "#290068",
        "inverse-primary": "#9187fb",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-primary-fixed-variant": "#3f32a4",
        "primary-fixed": "#bfb9ff",
        "outline-variant": "#a2b1dd",
        "on-background": "#213156",
        "on-tertiary": "#f8f1ff",
        "on-secondary": "#e3fff6",
        "secondary-dim": "#005e50",
        "surface-container": "#eaedff",
        "on-tertiary-fixed-variant": "#4e00b7",
        "error-container": "#f76a80",
        "on-surface-variant": "#4f5e86"
      },
      fontFamily: {
        display: ['Poppins', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [tailwindAnimate],
};
export default config;
