# Generated by Django 6.0.4 on 2026-04-13 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inbox", "0002_contact_email_contact_phone"),
        ("orgs", "0004_organization_billing_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_domain",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("shop_id", models.CharField(blank=True, max_length=255, null=True)),
                ("access_token", models.BinaryField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopify_integrations",
                        to="orgs.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify Integration",
                "verbose_name_plural": "Shopify Integrations",
                "unique_together": {("org",)},
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SHOPIFY", "Shopify"),
                            ("WHATSAPP", "WhatsApp"),
                            ("MANUAL", "Manual"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("PROCESSING", "Processing"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("RETURNED", "Returned"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "shopify_order_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "shopify_customer_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                (
                    "customer_email",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="QAR", max_length=10)),
                ("line_items", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="inbox.contact",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="orgs.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "indexes": [
                    models.Index(
                        fields=["org", "status", "created_at"],
                        name="shopify_ord_org_id_909085_idx",
                    ),
                    models.Index(
                        fields=["org", "source", "created_at"],
                        name="shopify_ord_org_id_fb7566_idx",
                    ),
                    models.Index(
                        fields=["org", "contact"], name="shopify_ord_org_id_5fa881_idx"
                    ),
                    models.Index(
                        fields=["org", "created_at"],
                        name="shopify_ord_org_id_a0fa2a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AbandonedCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shopify_cart_token", models.CharField(max_length=255, unique=True)),
                (
                    "customer_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("line_items", models.JSONField(default=list)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="QAR", max_length=10)),
                ("checkout_url", models.TextField(blank=True)),
                ("recovery_sent_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abandoned_carts",
                        to="inbox.contact",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abandoned_carts",
                        to="orgs.organization",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abandoned_carts",
                        to="shopify.shopifyintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abandoned Cart",
                "verbose_name_plural": "Abandoned Carts",
                "indexes": [
                    models.Index(
                        fields=["org", "recovery_sent_at"],
                        name="shopify_aba_org_id_3ee2f6_idx",
                    ),
                    models.Index(
                        fields=["org", "converted_at"],
                        name="shopify_aba_org_id_3e4bab_idx",
                    ),
                ],
            },
        ),
    ]
