# Generated by Django 6.0.4 on 2026-04-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify", "0002_shopifyintegration_client_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, help_text="Shopify order number e.g. #1001", max_length=50
            ),
        ),
    ]
