# Generated by Django 6.0.4 on 2026-04-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Stripe event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('ignored', 'Ignored')], max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Exception message on failure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='billing_web_status_f0d6a6_idx')],
            },
        ),
    ]
