# Generated by Django 6.0.4 on 2026-04-14 21:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0006_flaggedorg'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_token_budget', models.IntegerField(default=50000, help_text='Monthly budget for Free plan')),
                ('starter_token_budget', models.IntegerField(default=500000, help_text='Monthly budget for Starter plan')),
                ('pro_token_budget', models.IntegerField(default=5000000, help_text='Monthly budget for Pro plan')),
                ('enterprise_token_budget', models.IntegerField(default=50000000, help_text='Monthly budget for Enterprise plan')),
                ('claude_input_cost_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.003000'), max_digits=8)),
                ('claude_output_cost_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.015000'), max_digits=8)),
                ('openai_input_cost_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.002000'), max_digits=8)),
                ('openai_output_cost_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.008000'), max_digits=8)),
                ('gemini_input_cost_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.000750'), max_digits=8)),
                ('gemini_output_cost_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.002250'), max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Clerk user ID of last editor', max_length=255)),
            ],
            options={
                'verbose_name': 'Admin Config',
                'verbose_name_plural': 'Admin Config',
            },
        ),
        migrations.CreateModel(
            name='RateLimitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='BUDGET_EXCEEDED, COST_CAP_EXCEEDED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_events', to='orgs.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org', 'created_at'], name='admin_panel_org_id_663d4c_idx')],
            },
        ),
    ]
