# Generated by Django 6.0.4 on 2026-04-12 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0002_organization_budget_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("tokens_in", models.IntegerField(default=0)),
                ("tokens_out", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ar", "Arabic"),
                            ("en", "English"),
                            ("bilingual", "Bilingual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fashion", "Fashion"),
                            ("food", "Food"),
                            ("electronics", "Electronics"),
                            ("beauty", "Beauty"),
                            ("home", "Home"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("casual", "Casual"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cache_hit", models.BooleanField(default=False)),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usages",
                        to="orgs.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage",
                "verbose_name_plural": "AI Usage Records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["org", "created_at"],
                        name="generate_ai_org_id_ae0a49_idx",
                    ),
                    models.Index(
                        fields=["org", "success"], name="generate_ai_org_id_83681b_idx"
                    ),
                ],
            },
        ),
    ]
