import type { Order, OrderListResponse, OrderSummaryResponse } from '@/lib/orders'

export const DUMMY_ORDERS: Order[] = [
  // PENDING
  {
    id: 1,
    source: 'SHOPIFY',
    status: 'PENDING',
    shopify_order_id: 'SH-10021',
    customer_name: 'أحمد المنصوري',
    customer_email: 'ahmed.mansouri@gmail.com',
    total_amount: '1250.00',
    currency: 'QAR',
    line_items: [
      { title: 'عطر عود الملكي', quantity: 2, price: '450.00' },
      { title: 'بخور مجلس', quantity: 1, price: '350.00' },
    ],
    contact_id: 1,
    contact_name: 'أحمد المنصوري',
    notes: 'يرجى التغليف الفاخر',
    created_at: '2026-04-13T08:10:00Z',
    updated_at: '2026-04-13T08:10:00Z',
  },
  {
    id: 2,
    source: 'WHATSAPP',
    status: 'PENDING',
    shopify_order_id: null,
    customer_name: 'فاطمة الشمري',
    customer_email: null,
    total_amount: '620.00',
    currency: 'QAR',
    line_items: [{ title: 'عباية حرير مطرزة', quantity: 1, price: '620.00' }],
    contact_id: 2,
    contact_name: 'فاطمة الشمري',
    notes: '',
    created_at: '2026-04-13T09:45:00Z',
    updated_at: '2026-04-13T09:45:00Z',
  },
  {
    id: 3,
    source: 'MANUAL',
    status: 'PENDING',
    shopify_order_id: null,
    customer_name: 'محمد العتيبي',
    customer_email: 'mohammad.otaibi@hotmail.com',
    total_amount: '3800.00',
    currency: 'QAR',
    line_items: [
      { title: 'ساعة فضية كلاسيك', quantity: 1, price: '3200.00' },
      { title: 'حقيبة جلدية', quantity: 1, price: '600.00' },
    ],
    contact_id: null,
    contact_name: null,
    notes: 'طلب خاص من معرض الرياض',
    created_at: '2026-04-12T14:30:00Z',
    updated_at: '2026-04-12T14:30:00Z',
  },
  // CONFIRMED
  {
    id: 4,
    source: 'SHOPIFY',
    status: 'CONFIRMED',
    shopify_order_id: 'SH-10018',
    customer_name: 'نورة القحطاني',
    customer_email: 'noura.q@gmail.com',
    total_amount: '890.00',
    currency: 'QAR',
    line_items: [
      { title: 'كريم وجه بالسدر', quantity: 3, price: '180.00' },
      { title: 'زيت أرجان طبيعي', quantity: 2, price: '175.00' },
    ],
    contact_id: 3,
    contact_name: 'نورة القحطاني',
    notes: '',
    created_at: '2026-04-11T11:20:00Z',
    updated_at: '2026-04-12T08:00:00Z',
  },
  {
    id: 5,
    source: 'WHATSAPP',
    status: 'CONFIRMED',
    shopify_order_id: null,
    customer_name: 'خالد الدوسري',
    customer_email: null,
    total_amount: '2200.00',
    currency: 'QAR',
    line_items: [{ title: 'طقم قهوة عربية (6 أشخاص)', quantity: 1, price: '2200.00' }],
    contact_id: 4,
    contact_name: 'خالد الدوسري',
    notes: 'هدية — يرجى إضافة بطاقة',
    created_at: '2026-04-11T16:00:00Z',
    updated_at: '2026-04-12T09:30:00Z',
  },
  // PROCESSING
  {
    id: 6,
    source: 'SHOPIFY',
    status: 'PROCESSING',
    shopify_order_id: 'SH-10015',
    customer_name: 'ريم الزهراني',
    customer_email: 'reem.zahrani@yahoo.com',
    total_amount: '450.00',
    currency: 'QAR',
    line_items: [{ title: 'عطر ورد الطائف', quantity: 1, price: '450.00' }],
    contact_id: 5,
    contact_name: 'ريم الزهراني',
    notes: '',
    created_at: '2026-04-10T10:00:00Z',
    updated_at: '2026-04-11T12:00:00Z',
  },
  {
    id: 7,
    source: 'MANUAL',
    status: 'PROCESSING',
    shopify_order_id: null,
    customer_name: 'عبدالله الرشيد',
    customer_email: 'abdullahrasheed@outlook.com',
    total_amount: '7500.00',
    currency: 'QAR',
    line_items: [
      { title: 'جلسة مجلس خشب عود', quantity: 1, price: '6000.00' },
      { title: 'مسند وسادة فاخر', quantity: 3, price: '500.00' },
    ],
    contact_id: null,
    contact_name: null,
    notes: 'توصيل داخل الرياض فقط',
    created_at: '2026-04-09T13:15:00Z',
    updated_at: '2026-04-11T15:00:00Z',
  },
  // SHIPPED
  {
    id: 8,
    source: 'SHOPIFY',
    status: 'SHIPPED',
    shopify_order_id: 'SH-10009',
    customer_name: 'سلمى العمري',
    customer_email: 'salma.omari@gmail.com',
    total_amount: '330.00',
    currency: 'QAR',
    line_items: [{ title: 'مجموعة شاي مغربي', quantity: 2, price: '165.00' }],
    contact_id: 6,
    contact_name: 'سلمى العمري',
    notes: '',
    created_at: '2026-04-07T09:00:00Z',
    updated_at: '2026-04-10T10:00:00Z',
  },
  {
    id: 9,
    source: 'WHATSAPP',
    status: 'SHIPPED',
    shopify_order_id: null,
    customer_name: 'يوسف البلوشي',
    customer_email: null,
    total_amount: '980.00',
    currency: 'QAR',
    line_items: [
      { title: 'بشت رجالي مطرز', quantity: 1, price: '850.00' },
      { title: 'غترة حرير', quantity: 2, price: '65.00' },
    ],
    contact_id: 7,
    contact_name: 'يوسف البلوشي',
    notes: '',
    created_at: '2026-04-06T14:45:00Z',
    updated_at: '2026-04-09T11:00:00Z',
  },
  // DELIVERED
  {
    id: 10,
    source: 'SHOPIFY',
    status: 'DELIVERED',
    shopify_order_id: 'SH-10003',
    customer_name: 'مريم الكعبي',
    customer_email: 'maryam.kaabi@gmail.com',
    total_amount: '1800.00',
    currency: 'QAR',
    line_items: [{ title: 'حقيبة يد لويس فيتون (نسخة الخليج)', quantity: 1, price: '1800.00' }],
    contact_id: 8,
    contact_name: 'مريم الكعبي',
    notes: '',
    created_at: '2026-04-01T10:00:00Z',
    updated_at: '2026-04-05T16:00:00Z',
  },
  {
    id: 11,
    source: 'WHATSAPP',
    status: 'DELIVERED',
    shopify_order_id: null,
    customer_name: 'تركي السبيعي',
    customer_email: null,
    total_amount: '540.00',
    currency: 'QAR',
    line_items: [
      { title: 'قهوة إثيوبية فاخرة 500g', quantity: 3, price: '120.00' },
      { title: 'دلة تقليدية نحاس', quantity: 1, price: '180.00' },
    ],
    contact_id: 9,
    contact_name: 'تركي السبيعي',
    notes: '',
    created_at: '2026-04-02T08:30:00Z',
    updated_at: '2026-04-05T14:00:00Z',
  },
  {
    id: 12,
    source: 'MANUAL',
    status: 'DELIVERED',
    shopify_order_id: null,
    customer_name: 'حصة المطيري',
    customer_email: 'hessa.mutairi@gmail.com',
    total_amount: '220.00',
    currency: 'QAR',
    line_items: [{ title: 'ملابس أطفال (3 قطع)', quantity: 1, price: '220.00' }],
    contact_id: null,
    contact_name: null,
    notes: '',
    created_at: '2026-04-03T12:00:00Z',
    updated_at: '2026-04-06T09:00:00Z',
  },
  // RETURNED
  {
    id: 13,
    source: 'SHOPIFY',
    status: 'RETURNED',
    shopify_order_id: 'SH-9998',
    customer_name: 'بدر الحربي',
    customer_email: 'badr.harbi@hotmail.com',
    total_amount: '750.00',
    currency: 'QAR',
    line_items: [{ title: 'حذاء جلد إيطالي', quantity: 1, price: '750.00' }],
    contact_id: 10,
    contact_name: 'بدر الحربي',
    notes: 'المقاس غير مناسب — إرجاع كامل',
    created_at: '2026-03-28T11:00:00Z',
    updated_at: '2026-04-02T10:00:00Z',
  },
]

export const DUMMY_ORDER_LIST_RESPONSE: OrderListResponse = {
  count: DUMMY_ORDERS.length,
  next: null,
  previous: null,
  results: DUMMY_ORDERS,
}

export const DUMMY_ORDER_SUMMARY: OrderSummaryResponse = {
  month: 'April 2026',
  total_amount: '20330.00',
  currency: 'QAR',
  by_source: {
    SHOPIFY: { count: 6, amount: '12470.00' },
    WHATSAPP: { count: 5, amount: '5340.00' },
    MANUAL: { count: 2, amount: '11720.00' },
  },
}
