# Generated by Django 6.0.4 on 2026-04-13 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0004_organization_billing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp Business'), ('FACEBOOK', 'Facebook')], max_length=20)),
                ('platform_id', models.CharField(db_index=True, help_text='Unique ID assigned by the platform (e.g., Instagram user PSID).', max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('ai_score', models.IntegerField(default=0, help_text='Lead score 0-100. Incremented/decremented by AI pipeline on each message.')),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, help_text='Cumulative order value attributed to this contact (QAR).', max_digits=12)),
                ('tags', models.JSONField(default=list, help_text='Free-form string tags set by the merchant.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='orgs.organization')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-ai_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp Business'), ('FACEBOOK', 'Facebook')], max_length=20)),
                ('access_token', models.BinaryField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('page_id', models.CharField(blank=True, help_text='Instagram/Facebook Page ID. Null for WhatsApp.', max_length=255, null=True)),
                ('phone_number_id', models.CharField(blank=True, help_text='WhatsApp Business phone number ID. Null for Instagram/Facebook.', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_channels', to='orgs.organization')),
            ],
            options={
                'verbose_name': 'Social Channel',
                'verbose_name_plural': 'Social Channels',
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp Business'), ('FACEBOOK', 'Facebook')], max_length=20)),
                ('platform_msg_id', models.CharField(db_index=True, max_length=255)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=10)),
                ('content', models.TextField(help_text='Original message content.')),
                ('content_ar', models.TextField(blank=True, help_text='Arabic translation of content (set by AI pipeline for INBOUND messages).')),
                ('intent', models.CharField(blank=True, choices=[('READY_TO_BUY', 'Ready to Buy'), ('PRICE_INQUIRY', 'Price Inquiry'), ('INFO_REQUEST', 'Info Request'), ('COMPLAINT', 'Complaint'), ('BROWSING', 'Browsing')], help_text='AI-classified message intent. Null until pipeline runs.', max_length=20, null=True)),
                ('ai_draft', models.TextField(blank=True, help_text='AI-generated English reply draft.')),
                ('ai_draft_ar', models.TextField(blank=True, help_text='AI-generated Arabic (Gulf dialect) reply draft.')),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp from the platform. Null for manually-created messages.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.contact')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orgs.organization')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='inbox.socialchannel')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-sent_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['org', 'platform'], name='inbox_conta_org_id_c5f2da_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['org', 'ai_score'], name='inbox_conta_org_id_00a718_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('org', 'platform', 'platform_id')},
        ),
        migrations.AddIndex(
            model_name='socialchannel',
            index=models.Index(fields=['org', 'is_active'], name='inbox_socia_org_id_4732bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialchannel',
            unique_together={('org', 'platform')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['org', 'contact', 'created_at'], name='inbox_messa_org_id_afa98d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['org', 'read', 'created_at'], name='inbox_messa_org_id_dcac7a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['org', 'intent'], name='inbox_messa_org_id_4514e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('platform', 'platform_msg_id')},
        ),
    ]
