# Generated by Django 6.0.4 on 2026-04-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Customer email. Used for Shopify order attribution.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Customer phone (E.164 preferred). Used as fallback attribution.",
                max_length=30,
                null=True,
            ),
        ),
    ]
