# Generated by Django 6.0.4 on 2026-04-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_tiktok_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='platform',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp Business'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('SHOPIFY', 'Shopify')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='platform',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp Business'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialchannel',
            name='platform',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp Business'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('SHOPIFY', 'Shopify')], max_length=20),
        ),
    ]
