# Generated by Django 6.0.4 on 2026-04-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_alter_contact_platform_alter_message_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
