# Generated by Django 6.0.4 on 2026-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="generations_used_this_month",
            field=models.IntegerField(
                default=0,
                help_text="Counter incremented atomically via F() after each successful generation.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="monthly_generation_limit",
            field=models.IntegerField(
                default=20,
                help_text="Maximum AI generations allowed per month. Free plan default = 20.",
            ),
        ),
    ]
