# Generated by Django 6.0.4 on 2026-04-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_flaggedorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onboarding_state',
            field=models.JSONField(blank=True, default=dict, help_text='Onboarding progress: created_workspace, connected_channel, first_generation, invited_teammate.'),
        ),
    ]
